### ISSUE TITLE
TODO: bring back the StaticArrays performance improvements

### ISSUE THREAD

**Issue by rdeits** [JuliaAlgebra/TypedPolynomials.jl#29]
@dpsanders showed me a nice performance test from https://github.com/JuliaDiff/TaylorSeries.jl/blob/master/perf/fateman.jl

```julia
function fateman1(degree)
    @polyvar x y z w
    s = (1 + x + y + z + w)^degree
    s * (s + 1)
end
```

Currently this package is slower than MultivariatePolynomials for degree > 5. Bringing back StaticArrays will help, and I will see what other performance optimizations are possible. 

StaticArrays can come back in as soon as they tag a new release.

**Comment by blegat** [comment]
We were looking for good benchmarks, here is one ! I am suprised that `TypedPolynomials` is not the faster here though.

**Comment by dpsanders** [comment]
Cc @lbenet, who found the Fateman benchmark.

**Comment by rdeits** [comment]
Yeah, I was surprised too. I'll have to look at what's going on after JuliaCon :)
