### ISSUE TITLE
Publish Package?

### ISSUE THREAD

**Issue by saschatimme** [JuliaAlgebra/TypedPolynomials.jl#36]
Are there any blockers to get the package released? @rdeits @blegat

**Comment by blegat** [comment]
None for me. @rdeits ?

**Comment by rdeits** [comment]
Nope, I haven't used this in a few months (I'm currently not doing anything that needs high-performance polynomials), but I'd be happy to have this published. I guess we just need a readme.

**Comment by rdeits** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/13664 (finally!)

**Comment by saschatimme** [comment]
Really cool! :)
