### ISSUE TITLE
Endless loop in 0.7 during package loading

### ISSUE THREAD

**Issue by saschatimme** [JuliaAlgebra/TypedPolynomials.jl#44]
It seems that the package gets somewhere stuck during package loading. I did not investigate further where exactly this happens.

**Comment by blegat** [comment]
Shouldn't we open an issue in JuliaLang/julia ?

**Comment by saschatimme** [comment]
Yes we should, I just didn't have time (so far) to figure out where exactly things break.

**Comment by saschatimme** [comment]
Okay false alarm, this was only because of a deprecation which went rogue. So far things were easy to update, but I got some strange warnings
```julia
┌ Warning: Deprecated syntax `implicit assignment to global variable `x``.
│ Use `global x` instead.
└ @ none:0
```
Do you know what this could be @rdeits?

**Comment by rdeits** [comment]
That warning usually means you have something like: 

```julia
x = ...

...
...
..

for i in 1:10
  x = ...
end
```

Currently, that `for` loop will overwrite the global `x`, but in the future it will not, hence the deprecation warning. 

However, without some sense of what line is triggering the warning it's hard to say what exactly is causing it.

**Comment by saschatimme** [comment]
The things is I cannot reproduce it in the REPL. Here is a Travis log where you can see plenty of these warnings
https://travis-ci.org/JuliaAlgebra/TypedPolynomials.jl/jobs/413301064 . All are occurring in the interface tests, which is weird since for DynamicPolynomials there are no such warnings.

**Comment by saschatimme** [comment]
Okay the reason for this was the `demo.ipynb` notebook which was included. I moved this to the last place, and everything works now without these warnings.
