### ISSUE TITLE
overwritten in promotion.jl

### ISSUE THREAD

**Issue by vavrines** [JuliaAlgebra/TypedPolynomials.jl#72]
It seems that line 58 in promotion.jl
https://github.com/JuliaAlgebra/TypedPolynomials.jl/blob/a4e39ee98973000556e7dcc5d8d85ed271779b15/src/promotion.jl#L58 

is a duplicate of 56
https://github.com/JuliaAlgebra/TypedPolynomials.jl/blob/a4e39ee98973000556e7dcc5d8d85ed271779b15/src/promotion.jl#L56

so it throws this warning during precompilation
```
WARNING: Method definition promote_rule(Type{TypedPolynomials.Term{C, M1} where C}, Type{TypedPolynomials.Term{T, M2}}) where {T, M1, M2} in module TypedPolynomials at /home2/vavrines/.julia/packages/TypedPolynomials/oORum/src/promotion.jl:58 overwritten at /home2/vavrines/.julia/packages/TypedPolynomials/oORum/src/promotion.jl:56.
  ** incremental compilation may be fatally broken for this module **
```

**Comment by blegat** [comment]
Indeed thanks!
